name: Trigger stats

on:
  workflow_dispatch:
  schedule:
    - cron: '17 7 * * *'

jobs:
  trigger_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run main script
        run: pip install -r requirements.txt && python main.py
        env:
          HDX_API_TOKEN: ${{ secrets.HDX_API_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit updated sources
        with:
          commit_message: automatic - data updated
